# Generated by Django 2.1.1 on 2018-09-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartGenerator', '0002_auto_20180917_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='colored',
            field=models.BooleanField(default=True, verbose_name='Colored'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='numSamplesU',
            field=models.FloatField(default=50, verbose_name='numSamplesU'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='numSamplesV',
            field=models.FloatField(default=10, verbose_name='numSamplesV'),
        ),
    ]
